# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_services/video_analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_services/video_analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"grpc_services/video_analysis.proto\x12\x0evideo_analysis\"!\n\x0cVideoRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"\"\n\x0cTextResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\"3\n\x10\x41nalysisResponse\x12\x0f\n\x07objects\x18\x01 \x03(\t\x12\x0e\n\x06graphs\x18\x02 \x03(\t\"7\n\rReportRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x13\n\x0breport_type\x18\x02 \x01(\t\"%\n\x0eReportResponse\x12\x13\n\x0breport_path\x18\x01 \x01(\t\"6\n\x14\x43larificationRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07options\x18\x02 \x03(\t\"R\n\x15\x43larificationResponse\x12\x17\n\x0fselected_option\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07options\x18\x03 \x03(\t\" \n\x0eHistoryRequest\x12\x0e\n\x06last_n\x18\x01 \x01(\x05\"#\n\x0fHistoryResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2\xaf\x03\n\rVideoAnalysis\x12M\n\x0fTranscribeVideo\x12\x1c.video_analysis.VideoRequest\x1a\x1c.video_analysis.TextResponse\x12N\n\x0c\x41nalyzeVideo\x12\x1c.video_analysis.VideoRequest\x1a .video_analysis.AnalysisResponse\x12O\n\x0eGenerateReport\x12\x1d.video_analysis.ReportRequest\x1a\x1e.video_analysis.ReportResponse\x12[\n\x0c\x43larifyQuery\x12$.video_analysis.ClarificationRequest\x1a%.video_analysis.ClarificationResponse\x12Q\n\x0eGetChatHistory\x12\x1e.video_analysis.HistoryRequest\x1a\x1f.video_analysis.HistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_services.video_analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOREQUEST']._serialized_start=54
  _globals['_VIDEOREQUEST']._serialized_end=87
  _globals['_TEXTRESPONSE']._serialized_start=89
  _globals['_TEXTRESPONSE']._serialized_end=123
  _globals['_ANALYSISRESPONSE']._serialized_start=125
  _globals['_ANALYSISRESPONSE']._serialized_end=176
  _globals['_REPORTREQUEST']._serialized_start=178
  _globals['_REPORTREQUEST']._serialized_end=233
  _globals['_REPORTRESPONSE']._serialized_start=235
  _globals['_REPORTRESPONSE']._serialized_end=272
  _globals['_CLARIFICATIONREQUEST']._serialized_start=274
  _globals['_CLARIFICATIONREQUEST']._serialized_end=328
  _globals['_CLARIFICATIONRESPONSE']._serialized_start=330
  _globals['_CLARIFICATIONRESPONSE']._serialized_end=412
  _globals['_HISTORYREQUEST']._serialized_start=414
  _globals['_HISTORYREQUEST']._serialized_end=446
  _globals['_HISTORYRESPONSE']._serialized_start=448
  _globals['_HISTORYRESPONSE']._serialized_end=483
  _globals['_VIDEOANALYSIS']._serialized_start=486
  _globals['_VIDEOANALYSIS']._serialized_end=917
# @@protoc_insertion_point(module_scope)
