# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_services import video_analysis_pb2 as grpc__services_dot_video__analysis__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_services/video_analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoAnalysisStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeVideo = channel.unary_unary(
                '/video_analysis.VideoAnalysis/TranscribeVideo',
                request_serializer=grpc__services_dot_video__analysis__pb2.VideoRequest.SerializeToString,
                response_deserializer=grpc__services_dot_video__analysis__pb2.TextResponse.FromString,
                _registered_method=True)
        self.AnalyzeVideo = channel.unary_unary(
                '/video_analysis.VideoAnalysis/AnalyzeVideo',
                request_serializer=grpc__services_dot_video__analysis__pb2.VideoRequest.SerializeToString,
                response_deserializer=grpc__services_dot_video__analysis__pb2.AnalysisResponse.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/video_analysis.VideoAnalysis/GenerateReport',
                request_serializer=grpc__services_dot_video__analysis__pb2.ReportRequest.SerializeToString,
                response_deserializer=grpc__services_dot_video__analysis__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.ClarifyQuery = channel.unary_unary(
                '/video_analysis.VideoAnalysis/ClarifyQuery',
                request_serializer=grpc__services_dot_video__analysis__pb2.ClarificationRequest.SerializeToString,
                response_deserializer=grpc__services_dot_video__analysis__pb2.ClarificationResponse.FromString,
                _registered_method=True)
        self.GetChatHistory = channel.unary_unary(
                '/video_analysis.VideoAnalysis/GetChatHistory',
                request_serializer=grpc__services_dot_video__analysis__pb2.HistoryRequest.SerializeToString,
                response_deserializer=grpc__services_dot_video__analysis__pb2.HistoryResponse.FromString,
                _registered_method=True)


class VideoAnalysisServicer(object):
    """Service definition
    """

    def TranscribeVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClarifyQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeVideo,
                    request_deserializer=grpc__services_dot_video__analysis__pb2.VideoRequest.FromString,
                    response_serializer=grpc__services_dot_video__analysis__pb2.TextResponse.SerializeToString,
            ),
            'AnalyzeVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeVideo,
                    request_deserializer=grpc__services_dot_video__analysis__pb2.VideoRequest.FromString,
                    response_serializer=grpc__services_dot_video__analysis__pb2.AnalysisResponse.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=grpc__services_dot_video__analysis__pb2.ReportRequest.FromString,
                    response_serializer=grpc__services_dot_video__analysis__pb2.ReportResponse.SerializeToString,
            ),
            'ClarifyQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ClarifyQuery,
                    request_deserializer=grpc__services_dot_video__analysis__pb2.ClarificationRequest.FromString,
                    response_serializer=grpc__services_dot_video__analysis__pb2.ClarificationResponse.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=grpc__services_dot_video__analysis__pb2.HistoryRequest.FromString,
                    response_serializer=grpc__services_dot_video__analysis__pb2.HistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_analysis.VideoAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('video_analysis.VideoAnalysis', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoAnalysis(object):
    """Service definition
    """

    @staticmethod
    def TranscribeVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video_analysis.VideoAnalysis/TranscribeVideo',
            grpc__services_dot_video__analysis__pb2.VideoRequest.SerializeToString,
            grpc__services_dot_video__analysis__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video_analysis.VideoAnalysis/AnalyzeVideo',
            grpc__services_dot_video__analysis__pb2.VideoRequest.SerializeToString,
            grpc__services_dot_video__analysis__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video_analysis.VideoAnalysis/GenerateReport',
            grpc__services_dot_video__analysis__pb2.ReportRequest.SerializeToString,
            grpc__services_dot_video__analysis__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClarifyQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video_analysis.VideoAnalysis/ClarifyQuery',
            grpc__services_dot_video__analysis__pb2.ClarificationRequest.SerializeToString,
            grpc__services_dot_video__analysis__pb2.ClarificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video_analysis.VideoAnalysis/GetChatHistory',
            grpc__services_dot_video__analysis__pb2.HistoryRequest.SerializeToString,
            grpc__services_dot_video__analysis__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
